---

# see https://askubuntu.com/a/664806/325
# for how to set proxy system-wide
- name: Use ETHZ HTTP proxy for HTTP/FTP access (CentOS/RHEL)
  lineinfile:
    path: /etc/environment
    line: "{{item}}_proxy=http://proxy.ethz.ch:3128/"
    state: present
    create: yes
  loop:
    - ftp
    - http
    - https


- name: No proxy for local domains (CentOS/RHEL)
  lineinfile:
    path: /etc/environment
    line: "no_proxy=localhost,127.0.0.1,169.254.169.254,.ethz.ch,172.31.33.64/26"
    state: present
    create: yes
