---

# see https://askubuntu.com/a/664806/325
# for how to set proxy system-wide
- name: Use ETHZ HTTP proxy for HTTP/FTP access (CentOS/RHEL)
  lineinfile:
    path: /etc/environment
    line: "{{item.proto}}_proxy={{item.scheme}}://proxy.ethz.ch:3128/"
    state: present
    create: yes
  loop:
    - { proto: ftp,   scheme: http }
    - { proto: http,  scheme: http }
    - { proto: https, scheme: https }


- name: No proxy for local domains (CentOS/RHEL)
  lineinfile:
    path: /etc/environment
    line: "no_proxy=localhost,127.0.0.1,169.254.169.254,.ethz.ch"
    state: present
    create: yes
