---

- name: download official images
  tags:
    - download
  hosts: localhost
  gather_facts: no

  vars_files:
    - conf.yml

  tasks:
    - name: create new file `downloaded.yml`
      copy:
        dest: 'vars/downloaded.yml'
        content: |
          ---

    - include_tasks: 'tasks/download.yml'
      vars:
        source: '{{ img.source }}'
        dest: '{{ img.source|basename }}'
        format: '{{ img.format|default("qcow2") }}'
        name: '{{ img.name }}'
        raw: '{{ img.source|basename|splitext|first }}.raw'
        use_virtio_scsi: '{{ img.use_virtio_scsi|default("yes") }}'
      with_items: '{{ images }}'
      loop_control:
        loop_var: img


- name: start VMs
  tags:
    - start
  hosts: localhost
  gather_facts: no

  vars:
    # uzh-only network
    network: c86b320c-9542-4032-a951-c8a068894cc2

  vars_prompt:
    - name: 'keypair'
      prompt: 'Name of OpenStack keypair to authorize for SSH connections'
      private: no

  tasks:

    # we cannot use `vars_files:` for this, as the file is parsed at Ansible
    # startup time, before the above play gets to modify it
    - include_vars:
        file: conf.yml

    - include_vars:
        file: 'downloaded.yml'
        name: uuid_of

    - include_tasks: 'tasks/start.yml'
      vars:
        name: '{{ img.name }}'
        uuid: '{{ uuid_of[img.name] }}'
        user: '{{ img.user }}'
        extra_plays: '{{ img.extra_plays|default([]) }}'
        extra_prefix: '{{ img.extra_prefix|default("") }}'
      with_items: '{{ images }}'
      loop_control:
        loop_var: img


# this is a separate play so that the `gather_facts:` step runs on all the VMs
# that were created in the "start" phase
- name: update VM image
  tags:
    - update
  hosts: targets
  gather_facts: yes
  become: yes

  tasks:
    # we cannot use `vars_files:` for this, as the file is parsed at Ansible
    # startup time, before the above play gets to modify it
    - include_vars:
        file: conf.yml

    # - name: print info for debugging
    #   debug:
    #     var: hostvars

    - include_tasks: '{{ play }}'
      loop_control:
        loop_var: 'play'
      with_first_found:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - 'default.yml'

    - include_tasks: '{{ play }}'
      loop_control:
        loop_var: 'play'
      with_items: '{{ extra_plays }}'


# this is a separate play to re-run the `gather_facts:` step;
# we want vars like `ansible_distribution_version` to be up-to-date
# in case the last steps changed it (e.g., minor release upgrade)
- name: make VM snapshot
  tags:
    - snapshot
  hosts: targets
  gather_facts: yes

  vars_prompt:
    - name: 'prefix'
      prompt: 'Prefix for the all new snapshot names'
      default: '*** '
      private: no

  tasks:
    # we cannot use `vars_files:` for this, as the file is parsed at Ansible
    # startup time, before the above play gets to modify it
    - include_vars:
        file: conf.yml

    - include_vars:
        file: 'downloaded.yml'
        name: uuid_of

    - import_tasks: 'tasks/cleanup.yml'
      become: yes

    # we need to shutdown VM after cleanup to ensure that the root disk is clean
    - name: shutdown VM instance
      shell: |
        openstack server stop "{{ instance_uuid }}"; sleep 30; openstack server show -c status "{{ instance_uuid }}" | grep SHUTOFF
      register: cmd_result
      retries: 10
      until: cmd_result | success
      become: no
      delegate_to: localhost


    - name: make VM snapshot
      shell: |
        nova image-create --poll "{{ instance_uuid }}" "{{ prefix }}{{ extra_prefix|default('') }}{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_date_time.date}})"
      become: no
      delegate_to: localhost

    # command `openstack image unset` fails if some properties are
    # *not* already set on the image; so split its invocation in two
    # parts: remove properties that are for sure set on any image, and
    # remove properties that are only set on some -- ignore errors in
    # this latter case

    - name: turn snapshot back into image (1/2)
      become: no
      shell: |
        openstack image unset \
          --property image_location \
          --property image_state \
          --property image_type \
          --property kernel_id \
          --property owner_id \
          --property user_id \
          --property ramdisk_id \
          "{{ prefix }}{{ extra_prefix|default('') }}{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_date_time.date}})"
      delegate_to: localhost

    - name: turn snapshot back into image (2/2)
      become: no
      shell: |
        openstack image unset \
          --property hw_scsi_model \
          --property hw_disk_bus \
          "{{ prefix }}{{ extra_prefix|default('') }}{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_date_time.date}})";
      ignore_errors: yes
      delegate_to: localhost


- name: stop VMs
  tags:
    - stop
  hosts: localhost
  gather_facts: no

  vars_files:
    - conf.yml

  tasks:

    # we cannot use `vars_files:` for this, as the file is parsed at Ansible
    # startup time, before the above play gets to modify it
    - include_vars:
        file: 'downloaded.yml'
        name: uuid_of

    - name: stop VM instance
      os_server:
        name: 'sc-update-images-{{ uuid_of[img.name] }}-{{ img.name }}'
        state: absent
        wait: yes
      with_items: '{{ images }}'
      loop_control:
        loop_var: img
