---

- name: clean up VM before snapshot (package files)
  command: |
    apt-get clean -y
  become: yes
  when: 'ansible_os_family == "Debian"'

- name: clean up VM before snapshot (package files)
  command: |
    yum clean all
  become: yes
  when: 'ansible_os_family == "RedHat"'

- name: clean up VM before snapshot (system files)
  shell: |
    rm -r -f -v {{ item }}
  args:
    removes: '{{ item }}'
  become: yes
  with_items:
    - "/etc/cloud/uzh-customization-script"
    - "/var/lib/cloud/data/*"
    - "/var/lib/cloud/instance"
    - "/var/lib/cloud/instances/*"

- name: clean up VM before snapshot (user files)
  shell: |
    rm -r -f -v '{{ item[0] }}/{{ item[1] }}'
  args:
    removes: '{{ item[0] }}/{{ item[1] }}'
  become: yes
  with_nested:
    - ['/home/centos', '/home/debian', '/home/ubuntu', '/root', '{{ ansible_user_dir }}' ]
    - [".ansible", ".bash_history", ".cache", ".lesshst", ".ssh/authorized_keys", ".sudo_as_admin_successful", ".Xauthority", ".viminfo"]


- name: Trim root filesystem before snapshotting
  command: |
    fstrim /
  become: yes
  # XXX: `fstrim` may not be installed on all images,
  # or drivers may not support the FITRIM ioctl
  # so just ignore errors instead of trying to detect
  # when it should work and when not
  ignore_errors: yes
