---

- name: Download image from {{source}}
  get_url:
    url: '{{source_url}}'
    dest: './{{source_file}}'
    backup: yes


- name: Convert image file {{source_file}} to {{dest_format}} format
  command: |
    qemu-img convert -f {{source_format}} -O {{dest_format}} {{source_file}} {{dest_file}}
  args:
    creates: '{{dest_file}}'
  when: 'dest_format != source_format'


- name: Copy image file {{source_file}} to {{dest_file}}
  file:
    state: hard
    src: '{{ source_file }}'
    dest: '{{ dest_file }}'
  when: 'dest_format == source_format'


- name: Compute MD5 checksum of destination image file
  shell: |
    md5sum '{{dest_file}}' | cut -c 1-32
  register: image_md5sum


- name: Run cloud-specific upload tasks
  include_tasks: 'tasks/{{cloud}}/upload.yml'


- name: Write image UUID into vars file
  lineinfile:
    dest: 'vars/downloaded.yml'
    line: '{{name}}: {{image_uuid}}'
