---
#
# Stop a given instance.
#

- include_vars:
    file: 'instances.yml'
    name: instances

- name: stop VM instance
  one_vm:
    instance_ids: '{{ instances.ids }}'
    state: absent
    wait: yes
  with_items: '{{ images }}'
  loop_control:
    loop_var: img

- name: Delete upstream images
  include_tasks: 'rm_upstream_img.yml'
  vars:
    vm_id: '{{ item }}'
  loop: '{{ instances.ids }}'
