---
#
# Snapshot a VM to disk
#

- name: make VM snapshot
  shell: |
    nova image-create --poll "{{ instance_uuid }}" "{{ prefix }}{{ extra_prefix|default('') }}{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_date_time.date}})"
  become: no
  delegate_to: localhost

# command `openstack image unset` fails if some properties are
# *not* already set on the image; so split its invocation in two
# parts: remove properties that are for sure set on any image, and
# remove properties that are only set on some -- ignore errors in
# this latter case

- name: turn snapshot back into image (1/2)
  become: no
  shell: |
    openstack image unset \
      --property image_location \
      --property image_state \
      --property image_type \
      --property kernel_id \
      --property owner_id \
      --property user_id \
      --property ramdisk_id \
      "{{ prefix }}{{ extra_prefix|default('') }}{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_date_time.date}})"
  delegate_to: localhost

- name: turn snapshot back into image (2/2)
  become: no
  shell: |
    openstack image unset \
      --property hw_scsi_model \
      --property hw_disk_bus \
      "{{ prefix }}{{ extra_prefix|default('') }}{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_date_time.date}})";
  ignore_errors: yes
  delegate_to: localhost
