---
#
# Snapshot a VM to disk
#

- name: make VM snapshot
  shell: |
    nova image-create --poll "{{ instance_uuid }}" "{{ prefix }}{{ extra_prefix|default('') }}{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_date_time.date}})"
  become: no
  delegate_to: localhost

# command `openstack image unset` fails if some properties are
# *not* already set on the image; so just ignore errors, presuming
# this latter case.

- name: turn snapshot back into image
  become: no
  shell: |
    openstack image unset \
      --property image_location \
      --property image_state \
      --property image_type \
      --property kernel_id \
      --property owner_id \
      --property user_id \
      --property ramdisk_id \
      {# needed on ETHZ VIO -#}
      --property base_image_ref \
      --property boot_roles \
      --property image_type \
      --property instance_uuid \
      {# optionally set by this script -#}
      --property hw_scsi_model \
      --property hw_disk_bus \
      "{{ prefix }}{{ extra_prefix|default('') }}{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_date_time.date}})";
  ignore_errors: yes
  delegate_to: localhost
