---
#
# Upload an image to OpenStack and set `image_uuid`
#

- name: Check for existing image on OpenStack
  shell: |
    openstack image list \
        --property 'md5sum={{image_md5sum.stdout}}' \
        -f value -c ID \
        | head -n 1
  register: image_list
  failed_when: 'image_list.stderr != ""'


- name: Set image UUID from `openstack image list`
  set_fact:
    image_uuid: '{{image_list.stdout}}'
  when: 'image_list.stdout|length != 0'


- name: Upload image to OpenStack
  # `openstack image create` works almost exactly like `glance image-create` but
  # allows us to set the output format to YAML, which we can later on parse back
  # into Ansible variables
  shell: |
    openstack image create \
        --property 'md5sum={{image_md5sum.stdout}}' \
        --property 'source={{source_url}}' \
        {% if use_virtio_scsi -%}
        --property hw_scsi_model=virtio-scsi \
        --property hw_disk_bus=scsi \
        {%- endif %}
        {% if properties -%}
          {% for key, value in properties.iteritems() %}
        --property '{{key}}={{value}}' \
          {%- endfor %}
        {%- endif %}
        --disk-format {{dest_format}} \
        --container-format bare \
        --file '{{dest_file}}' \
        -f yaml -c id '{{name}} [DO NOT USE]' \
        | cut -c5-  # extract UUID
  register: image_create
  failed_when: 'image_create.stderr != ""'
  when: 'image_list.stdout|length == 0'


- name: Set image UUID from `openstack image create`
  set_fact:
    image_uuid: '{{image_create.stdout}}'
  when: 'image_list.stdout|length == 0'
